### ISSUE TITLE
Footer CTA - Not Centered

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-material-tailwind#2]
Hello David.

I see a small issue on the footer CTA button.
Might look better to have the `text` and the `Contact US` button centered.

Please take a look. Ty!

*** *** *** ***
![image](https://user-images.githubusercontent.com/51070104/204146508-aea0b113-9395-4084-8064-a589a33d56c5.png)

**Comment by dha-stix** [comment]
It's been updated.

**Comment by app-generator** [comment]
Perfect. TY @dha-stix 

![image](https://user-images.githubusercontent.com/51070104/204149478-23efe853-b6d3-4b61-beff-8bc19542a49a.png)
