### ISSUE TITLE
Minor UI/UX - Sign Pages

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-material-tailwind#3]
Hello @dha-stix 

Action buttons are not aligned. 

On AUTH pages, all fields are centered. The exception is the action button:
Might look better to have also the button centered (signIN + SignUP)

Please take a look. Ty!

*** *** *** 
![image](https://user-images.githubusercontent.com/51070104/204149579-52581bfd-9b6f-422e-af69-cfc3e7b4bd61.png)

**Comment by dha-stix** [comment]
Hi @app-generator I just fixed this issue.

**Comment by dha-stix** [comment]
Hi @app-generator I just fixed this issue
