### ISSUE TITLE
JS Warnings/Errors in Browser Console 

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-material-tailwind#4]
Hello @dha-stix 

In the browser, the JS console has many warnings like below (all pages).

```log
react-dom.development.js:86 Warning: Invalid DOM property `stroke-linecap`. Did you mean `strokeLinecap`?

Warning: Invalid DOM property `stroke-linejoin`. Did you mean `strokeLinejoin`?
```

Would be nice to have a warning-free JS console. 

Please take a look. Ty! 

*** *** *** *** 

![image](https://user-images.githubusercontent.com/51070104/204149728-391ad778-16c2-4b3c-a37a-9c842a540fe7.png)

**Comment by dha-stix** [comment]
Hi @app-generator I just fixed this issue
